Fixing a NoneType check that was missing in _get_nodes()
A missing NoneType check was causing the code to crash, and throw a:
AttributeError: 'NoneType' object has no attribute 'get'